MvcBookStore/MvcBookStore/Controllers/BookStoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcBookStore.Models;
using MvcBookStore.Controllers;
//list
using PagedList;
using PagedList.Mvc;
namespace MvcBookStore.Controllers
{
    public class BookStoreController : Controller
    {
        //Tao 1 doi tuong chua tona bo CSDL tu dbQLBansach
        dbQLBansachDataContext data = new dbQLBansachDataContext();

        private List<SACH> Laysachmoi(int count)
        {
            //Sap xep giam dan theo Ngaycapnhat , lay gia tri count dong dau
            return data.SACHes.OrderByDescending(a => a.Ngaycapnhat).Take(count).ToList();
        }
        // GET: BookStore
        public ActionResult Index(int ? page)
        {
            //Tao bien quy dinh so san pham tren 1 trang
            int pageSize = 8;
            //Tao bien so trang
            int pageNum = (page ?? 1);
            //Lay nhung quyen sach moi nhat
            var sachmoi = Laysachmoi(16);
            return View(sachmoi.ToPagedList(pageNum,pageSize));
        }
        //Them chu de voi tung muc nav
        public ActionResult Loai()
        {
            var loai = from cd in data.Loais select cd;
            return PartialView(loai);
        }
        //Them nha xuat ban voi tung muc nav
        public ActionResult Nhaxuatban()
        {
            var nhaxuatban = from nxb in data.NHAXUATBANs select nxb;
            return PartialView(nhaxuatban);
        }
        //Chia san pham theo chu de
        public ActionResult SPTheoloai(int id,int ? page)
        {
            //Tao bien quy dinh so san pham tren 1 trang
            int pageSize = 8;
            //Tao bien so trang
            int pageNum = (page ?? 1);
            var sach = from s in data.SACHes where s.MaLoai == id select s;
            return View(sach.ToPagedList(pageNum, pageSize));
        }
        //Chia san pham theo Nha Xuat Ban
        public ActionResult SPTheoNXB(int id, int? page)
        {
            //Tao bien quy dinh so san pham tren 1 trang
            int pageSize = 8;
            //Tao bien so trang
            int pageNum = (page ?? 1);
            var sach = from s in data.SACHes where s.MaNXB == id select s;
            return View(sach.ToPagedList(pageNum, pageSize));
        }
        //Lay thong tin chi tiet sach
        public ActionResult Details(int id)
        {
            var sach = from s in data.SACHes
                       where s.Masach == id
                       select s;
            return View(sach.Single());
        }
        public ActionResult Thoat()
        {
            Session["Taikhoan"] = null;
            return View();
        }
    }
}

MvcBookStore/MvcBookStore/Views/BookStore/Details.cshtml
<style>
    img {
        height: auto;
        width: auto;
    }
</style>
@{
    ViewBag.Title = @Model.Tensach;
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}
<h5>@Model.Tensach</h5>
<br />
<div class="col-12">
    <center><img class="hover-img col-4" src="~/images/anhsp/@Model.Anhbia" alt="@Model.Tensach"></center>
    <br />
</div>
<div class="col-12">
    <h6>Loại sách: @Model.Loai.TenLoai</h6>
    <h6>Nhà Xuất Bản: @Model.NHAXUATBAN.TenNXB</h6>
    <h6 class="danger">Giá bán: @String.Format("{0:#,##0}", @Model.Giaban) VNĐ</h6>
    <h6>Số lượng tồn: @Model.Soluongton quyển</h6>
    <h6>Mô tả: @Model.Mota</h6>
    <br />
</div>
@if (@Model.Soluongton != 0 && @Model.Soluongton != null)
{
    <div class="text-center">
        <button type="button" class="btn bg-primary" >
            <a href="@Url.Action("ThemGiohang","GioHang", new {@iMasach=@Model.Masach,@strURL=Request.Url.ToString()})">Đặt Mua</a>
        </button>
    </div>
}
else
{
    <div class="text-center">
        <button type="button" class="btn bg-danger">
            Hết Hàng!
        </button>
    </div>
}

MvcBookStore/MvcBookStore/Views/BookStore/Index.cshtml
@using MvcBookStore.Models
@using PagedList.Mvc;
@model PagedList.PagedList<SACH>
<style>
    .Trang li {
        display: inline;
        letter-spacing: 10px;
    }
</style>
@{
    ViewBag.Title = "Hải Long Store";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}
<h3 class="text-center">Sách mới cập nhật</h3>
<div class="row">
    @foreach (var sach in Model)
    {
        <div class="col-xl-3 col-lg-4 col-md-4 col-12">
            <div class="single-product">
                <div class="product-img">
                    <a href="@Url.Action("Details", "BookStore", new {id=sach.Masach})">
                        <img class="default-img" src="~/images/anhsp/@sach.Anhbia" alt="#">
                        <img class="hover-img" src="~/images/anhsp/@sach.Anhbia" alt="@sach.Tensach">
                    </a>
                    <div class="button-head">
                        <div class="product-action">
                            <a href="@Url.Action("Details", "BookStore", new {id=sach.Masach})" title="Thông tin chi tiết"><i class="ti-eye"></i><span>Xem nhanh</span></a>
                            <a title="Wishlist" href="#"><i class=" ti-heart "></i><span>Thêm vào yêu thích</span></a>
                        </div>
                        <div class="product-action-2">
                            @if (@sach.Soluongton != 0 && @sach.Soluongton != null)
                            {
                                <a href="@Url.Action("ThemGiohang","GioHang", new {@iMasach=@sach.Masach,@strURL=Request.Url.ToString()})">Thêm vào giỏ</a>
                            }
                        </div>
                    </div>
                </div>
                <div class="product-content text-center">
                    <h3><a href="@Url.Action("Details", "BookStore", new {id=sach.Masach})">@sach.Tensach</a></h3>
                    <div class="product-price">
                        @if (@sach.Soluongton != 0 && @sach.Soluongton != null)
                        {
                            <span>@String.Format("{0:#,##0}", @sach.Giaban)</span><span> VNĐ</span>
                        }
                        else
                        {
                            <span>Hết Hàng</span>
                        }
                    </div>
                </div>
            </div>
        </div>
    }
</div>
@*Tao lien ket giua cac trang*@
<div class="Trang">
    Trang @(Model.PageCount<Model.PageNumber?0:Model.PageNumber)/@Model.PageCount
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))
</div>

MvcBookStore/MvcBookStore/Views/BookStore/Loai.cshtml
@model IEnumerable<MvcBookStore.Models.Loai>
<li>
    <a href="#">Thể Loại<i class="ti-angle-down"></i></a>
    <ul class="dropdown">
        @foreach (var item in Model)
        {
            
            <li><a href="@Url.Action("SPTheoloai","BookStore",new {id=item.MaLoai})" class="list-group-item">@item.TenLoai</a></li>
            
        }
    <br/>
    </ul>
</li>

MvcBookStore/MvcBookStore/Views/BookStore/Nhaxuatban.cshtml
@model IEnumerable<MvcBookStore.Models.NHAXUATBAN>
<li>
    <a>Nhà Xuất Bản<i class="ti-angle-down"></i></a>
    <ul class="dropdown">
        @foreach (var item in Model)
        {
            <li><a href="@Url.Action("SPTheoNXB","BookStore",new {id=item.MaNXB})" class="list-group-item">@item.TenNXB</a></li>
        }
    <br/>
    </ul>
</li>

MvcBookStore/MvcBookStore/Views/BookStore/SPTheoNXB.cshtml
@using MvcBookStore.Models
@using PagedList.Mvc;
@model PagedList.PagedList<SACH>

<style>
    .Trang li {
        display: inline;
        letter-spacing: 20px;
    }

    .Trang a:active {
        background-color: green;
        text-decoration-color: green;
    }
</style>
@{
    ViewBag.Title = "Sách Theo Nhà Xuất Bản Trang"+ @Model.PageNumber;
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}
<h3 class="text-center">Sách theo Nhà Xuất Bản</h3>
<div class="row">
    @foreach (var sach in Model)
    {
        <div class="col-xl-3 col-lg-4 col-md-4 col-12">
            <div class="single-product">
                <div class="product-img">
                    <a href="@Url.Action("Details", "BookStore", new {id=sach.Masach})">
                        <img class="default-img" src="~/images/anhsp/@sach.Anhbia" alt="#">
                        <img class="hover-img" src="~/images/anhsp/@sach.Anhbia" alt="@sach.Tensach">
                    </a>
                    <div class="button-head">
                        <div class="product-action">
                            <a data-toggle="modal" data-target="#exampleModal" title="Theo thông tin" href="#"><i class=" ti-eye"></i><span>Xem nhanh</span></a>
                            <a title="Wishlist" href="#"><i class=" ti-heart "></i><span>Thêm vào yêu thích</span></a>
                        </div>
                        <div class="product-action-2">
                            @if (@sach.Soluongton != 0 && @sach.Soluongton != null)
                            {
                                <a href="@Url.Action("ThemGiohang","GioHang", new {@iMasach=sach.Masach,@strURL=Request.Url.ToString()})">Thêm vào giỏ</a>
                            }
                        </div>
                    </div>
                </div>
                <div class="product-content text-center">
                    <h3><a href="@Url.Action("Details", "BookStore", new {id=sach.Masach})">@sach.Tensach</a></h3>
                    <div class="product-price">
                        @if (@sach.Soluongton != 0 && @sach.Soluongton != null)
                        {
                            <span>@String.Format("{0:#,##0}", @sach.Giaban)</span><span> VNĐ</span>
                        }
                        else
                        {
                            <span>Hết Hàng</span>
                        }
                    </div>
                </div>
            </div>
        </div>
    }
</div>
<div class="Trang">
    Trang @(Model.PageCount<Model.PageNumber?0:Model.PageNumber)/@Model.PageCount
    @Html.PagedListPager(Model, page => Url.Action("SPTheoNXB", new { page = page }))
</div>  

MvcBookStore/MvcBookStore/Views/BookStore/SPTheoloai.cshtml
@using MvcBookStore.Models
@using PagedList.Mvc;
@model PagedList.PagedList<SACH>

<style>
    .Trang li {
        display: inline;
        letter-spacing: 20px;
    }
    .Trang a:active {
        background-color: green;
        text-decoration-color: green;
    }
</style>
@{
    ViewBag.Title = "Sách Theo Loại Trang "+ @Model.PageNumber;
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}
<h3 class="text-center">Sách xếp theo loại</h3>
<div class="row">
    @foreach (var sach in Model)
    {
        <div class="col-xl-3 col-lg-4 col-md-4 col-12">
            <div class="single-product">
                <div class="product-img">
                    <a href="@Url.Action("Details", "BookStore", new {id=sach.Masach})">
                        <img class="default-img" src="~/images/anhsp/@sach.Anhbia" alt="#">
                        <img class="hover-img" src="~/images/anhsp/@sach.Anhbia" alt="@sach.Tensach">
                    </a>
                    <div class="button-head">
                        <div class="product-action">
                            <a data-toggle="modal" data-target="#exampleModal" title="Xem thông tin" href="#"><i class=" ti-eye"></i><span>Xem nhanh</span></a>
                            <a title="Wishlist" href="#"><i class=" ti-heart "></i><span>Thêm vào yêu thích</span></a>
                        </div>
                        <div class="product-action-2">
                            @if (@sach.Soluongton != 0 && @sach.Soluongton != null)
                            {
                                <a href="@Url.Action("ThemGiohang","GioHang", new {@iMasach=@sach.Masach,@strURL=Request.Url.ToString()})">Thêm vào giỏ</a>
                            }
                        </div>
                    </div>
                </div>
                <div class="product-content text-center">
                    <h3><a href="@Url.Action("Details", "BookStore", new {id=sach.Masach})">@sach.Tensach</a></h3>
                    <div class="product-price">
                        @if (@sach.Soluongton != 0 && @sach.Soluongton != null)
                        {
                            <span>@String.Format("{0:#,##0}", @sach.Giaban)</span><span> VNĐ</span>
                        }
                        else
                        {
                            <span>Hết Hàng</span>
                        }
                    </div>
                </div>
            </div>
        </div>
    }
</div>
<div class="Trang">
    Trang @(Model.PageCount<Model.PageNumber?0:Model.PageNumber)/@Model.PageCount
    @Html.PagedListPager(Model, page => Url.Action("SPTheoloai", new { page = page }))
</div>

MvcBookStore/MvcBookStore/Views/BookStore/Thoat.cshtml
@{
    ViewBag.Title = "Đăng Xuất";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}
<h4>Đã đăng xuất! <br/>Xin cảm ơn @Session["TDN"].ToString() đã truy cập! </h4>
<br />
<h5 class="text-primary">
    @Html.ActionLink("Về Trang Chủ", "Index", "BookStore")
</h5>